### ISSUE TITLE
fix for automounter dependency chain on RH5

### ISSUE THREAD

**Issue by Phil-Friderici** [Ericsson/puppet-module-vas#59]
got this bug report:
> symptom: on RHEL 5 servers in the Hub after system boot the automounter does not use NIS maps - until it is restarted.
> root cause: an unlucky dependency chain in the services netfs, ypbind, vasypd, rsyslog, that cannot be resolved.
> 
> As a result, when VAS is installed or upgraded, it creates /etc/rc3.d/S28vasypd despite there is /etc/rc3.d/S27ypbind.
> Then, during a system boot, ypbind times out because it cannot bind to vasypd.
> And automounter, /etc/rc3.d/S28autofs, starts without NIS maps. Then puppet seems to see the missing ypbind and starts it - but too late for automounter.
> 
> Fix: run the following shell script:
> 
> cd /etc/rc3.d && test -f S27ypbind && test -f S28vasypd && mv S28vasypd S27vasypd
> 
> NB "test -f file" tests for a file, following a symbolic link. I.e. a stat() is performed.
> 
> That changes makes S27vasypd that comes before S27ypbind in the alphabet. (And then S28autofs > follows.) Because of the tiny change there cannot be an impact on other services.
> 
> Can we get this in Puppet?
> Scope is RHEL 5, but if the above checks are done then it will not change anything in other OS.
> Mininum would be "VAS install/upgrade", but at least for a short time should be rolled out everywhere.
> Logically it belongs to the VAS module.

coded this workaround and use it successfully since four weeks:
<pre>
class workarounds::automounter (
) {
  if "${::operatingsystem}-${::operatingsystemmajrelease}" == 'RedHat-5' {
    exec { "fix_rh5_automounter":
      command => 'mv /etc/rc3.d/S28vasypd /etc/rc3.d/S27vasypd',
      onlyif  => 'test -f /etc/rc3.d/S27ypbind && test -f /etc/rc3.d/S28vasypd',
      path    => '/bin:/usr/bin',
    }
  }
}
</pre>

Should I create a PR to integrate it into the vas module ?

**Comment by Phil-Friderici** [comment]
anyone ?

**Comment by propyless** [comment]
This should probably be reported as a bug to VAS, who can then fix this issue directly.

**Comment by Phil-Friderici** [comment]
yepp, you're right, the module should not manage broken packages.
